# Generated by Django 6.0 on 2026-01-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
